# Generated by Django 3.1 on 2020-08-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('expired', models.BooleanField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('movie', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='tbs.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbs.person')),
            ],
        ),
    ]
